services:
  palmpos_app:
    image: odoo:latest
    container_name: palmpos_app
    ports:
      - "8070:8069"
    volumes:
      - palmpos-web-data:/var/lib/odoo
      - ./app/config:/etc/odoo
      - ./app/addons:/mnt/extra-addons
    env_file:
      - ./app/.env
    environment:
      - HOST=${POSTGRES_HOST}
      - USER=${POSTGRES_USER}
      - PASSWORD=${POSTGRES_PASSWORD}
    restart: unless-stopped
    networks:
      palmpos_net_local:
        ipv4_address: 172.42.0.10
      web:        
    extra_hosts:
      - "host.docker.internal:host-gateway"

  palmpos_www:
    image: nginx:alpine
    container_name: palmpos_www
    ports:
      - "8071:80"
    volumes:
      - ./www/dist:/usr/share/nginx/html
      - ./www/nginx.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped
    networks:
      palmpos_net_local:
        ipv4_address: 172.42.0.11
      web:    
    depends_on:
      - palmpos_app

volumes:
  palmpos-web-data:

networks:
  palmpos_net_local:
    name: palmpos_net_local
    driver: bridge
    ipam:
      config:
        - subnet: 172.42.0.0/24
  web:
    external: true      
        